name: First_Workflow
on: [workflow_dispatch,push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5

      - name: Install Dependencies
        run: npm ci
        
      - name: Lint
        run: npm run lint 
  CodeTest:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: Install Dependencies
        run: npm ci
      - name: Test Code
        run: npm run test
  BuildCode:
    needs: CodeTest
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: Install Dependencies
        run: npm ci
      - name: Build Code
        run: npm run build
  deploy: 
    needs: BuildCode
    runs-on: ubuntu-latest
    steps:
    - name: Get Code
      uses: actions/checkout@v5
    - name: Install Dependencies
      run: npm ci
    - name: Deploying
      run: echo "Deploying ..."      
      

