name: Deployment First

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v5

      - name: Install Dependencies
        run: npm ci
        
      - name: Lint
        run: npm run lint

      - name: Test Code
        run: npm run test

      - name: Build Code
        run: npm run build

      - name: Deploying
        run: echo "Deploying ..."
